### ISSUE TITLE
Seltsame Gewichtsanzeige bzw. falsches Gewicht ESP8266

### ISSUE THREAD

**Issue by Skippydi** [nightflyer88/CG_scale#11]
Erstmal vielen Dank für die Software. Ich habe sie auf einem EP8266 installiert mit 2 Wägezellen (Rot von Aliexpress 5kg). Soweit funktioniert auch alles, aber das angezeigt Gewicht stimmt hinten und vorne nicht. Beim Kalibrieren habe ich ein Gewicht von 1711g SP 112.5mm eingesetzt, angezeigt wird nach dem kalibrieren 1712.9 und SP 113.4. Damit könnte ich leben. Aber beim normalen wiegen zeigt die Waage zwischen 1917g und 1735g an. Bei verschieden Wiegevorgängne habe ich niemals ein gleiches Gewicht, schon gar nicht das Kalibriergewicht. Woran könnte das liegen?
Danke für eine Antwort.

**Comment by nightflyer88** [comment]
Evtl. falsch verdrahtet oder Wiegezelle/HX711 defekt. Ist die Betriebsspannung der HX711 auf 3.3v stabilisiert ?

**Comment by Skippydi** [comment]
Die HX711 sind richtig verdrahtet,(mit separater Software getestet und auch nachkontrolliert),
 die 3.3 Volt liefert der ESP8266, sollte also auch ok sein. Seltsam ist nur das beim Kalibrieren das richtige Gewicht +/- 2 Gramm richtig berechnet wird.
Wenn ich jedoch meinen Segler wiege, der 460g wiegt, wird 682g angezeigt. Aber der berechnete SP stimmt fast zu 100% ( 54.2mm statt 55mm)
Ich bin echt ratlos.

**Comment by nightflyer88** [comment]
In den Einstellungen siehst du die Einzelgewichte der Zellen, belaste jede Zelle separat mit einem Gewicht, und prüfe was dabei angezeigt wird. Es könnte sein, dass eine Zelle defekt ist. Hast du die Abstände richtig eingegeben ? Was für Kalibrierwerte hast du ?

**Comment by Skippydi** [comment]
Hallo Nightflyer88, es tatsächlich eine Alumesszelle defekt. Habe ich ausgetauscht und jetzt sind die Messwerte und die Kalibrierung TOP!! Ganz herzlichen Dank für deine HIlfe. Die Messzelle funktionierte zwar, aber stellte sich nicht immer korrekt auf Null.
