### ISSUE TITLE
V2.2 Zu wenig Speicherplatz

### ISSUE THREAD

**Issue by chaoscrack** [nightflyer88/CG_scale#12]
Das hochladen der neuen Firmware ging gut. Jedoch beim upload des Filesystems erhielt ich die Fehlermeldung dass nicht genügend Speicherplatz vorhanden sei.
Um auszuschliessen dass der Speicher beim Update gelöscht wurde hab ich nochmals alles via pyFlascher hochgeladen und vorher den Speicher löschen lassen. Leider blieb das Problem das selbe.
<img width="477" alt="Bildschirmfoto 2020-11-02 um 21 38 53" src="https://user-images.githubusercontent.com/14803964/97917309-976ea000-1d54-11eb-99dd-30968bdf3a25.png">

**Comment by Rolf-G** [comment]
Hallo Patrick, ich hatte nach dem Laden der Firmware mit dem NodeMCU pyFlasher erst das Problem, das die update Seite nicht gefunden wurde (vermute, weil eine 1.x Version vorher drauf war) und die Webseiten noch die alten waren. Habe mir dann geholfen, indem ich das Filesystem einfach mit dem ESP8266 Sketch upload Tool im Arduino INO Programm hochgeladen habe.

**Comment by chaoscrack** [comment]
@Rolf-G 
Wie geschrieben hab ich mit dem flashen zuerst alles löschen lassen. Ohne Erfolg.
Update-Seite kann ich aufrufen. Nur anschliessend krieg ich die erwähnte Fehlermeldung.

Mittels Arduino IDE kann ich das Filesystem hochladen, doch ich verliere ich anschliessend immer wieder die Verbindung zum AccessPoint und kann somit auch nicht die Haupt- oder Setupseite aufrufen.

Wenn ich versuche den ESP via Arduino IDE zu flashen erhalte ich schon beim Kompilieren Fehlermeldungen. Diese lautet ` 'class HTTPClient' has no member named 'setRedirectLimit'` und die IDE steht bei der Zeile 1128 https.setRedirectLimit(0);

**Comment by chaoscrack** [comment]
Ich habs auch mit einem Wemos D1 mini V3.1.0 probiert. Die Fehlermeldungen sind die selben.
@nightflyer88 mach ich was falsch, oder wo könnte der Fehler liegen?

**Comment by nightflyer88** [comment]
ist mit V2.21 behoben
