### ISSUE TITLE
V2.2 crashed beim speichern von 3 Modellen

### ISSUE THREAD

**Issue by jraichle** [nightflyer88/CG_scale#14]
Hallo Michael,
wenn ich auf einen Wemos D1 mini die V2.2 installiere crashed diese sobald ich 3 x hintereinander ein neues Modell speichere. Danach startet auch der Wemos nicht mehr, da hilft dann nur ein komplettes neu flashen.
Mit der V2.0 tritt dieser Fehler nicht auf.

Viele Grüße
Jochen

**Comment by nightflyer88** [comment]
kannst du es mit V2.21 versuchen ? Ich hatte bei der V2.2 fälschlicherweise noch alte Librarys in meiner IDE

**Comment by jraichle** [comment]
Crashed auch mit der V2.21. Habe sowohl selber kompiliert (Bibliotheken sind upgedatet) als auch Dein Bin-File versucht. Crashed bei beiden, Habe es auf insgesamt 3 verschiedenen Wemos versucht, allerdings alle aus der gleichen Lieferung :-(  Schau jetzt mal ob ich noch einen anderen finde. Kannst Du denn mehrere Modelle mit der V2.21 anlegen?

**Comment by jraichle** [comment]
crashed auch auf einem Wemos aus einer anderen Lieferung. Bin echt gespannt ob Du mahr als 3 Modelle anlegen kannst; V2.0 funktioniert auf allen ohne Probleme

**Comment by nightflyer88** [comment]
Hab es auf die schnelle auch reproduzieren können, wobei ich 6 modelle anlegen konnte, bevor es gecrashed ist. Ich denke irgend ein Speicher läuft über. Kannst du versuchen in der settings.h die JSONDOC_SIZE zu erhöhen ?

**Comment by jraichle** [comment]
habe in der SettingsESP8266.h JSONDOC_SIZE von 20000 auf 30000 erhöht, crashed immer noch. Was wäre hier ein sinnvoller Wert?

**Comment by nightflyer88** [comment]
es ist die maximale grösse in byte der models.json datei. Versuch mal mit 100'000. Wie gross ist dein Speicher ? 4Mb?

**Comment by nightflyer88** [comment]
Sollte nun behoben sein: 19978a726989877e4be5a2f0c4494a4d5e224435

Kannst du es bei dir auch testen ?

**Comment by jraichle** [comment]
Hi Michael,
funktioniert!  Tollen Job gemacht :-)

Dankeschön
