### ISSUE TITLE
Nach Update, kein Zugriff mehr auf Web Oberfläche

### ISSUE THREAD

**Issue by fheinze26** [nightflyer88/CG_scale#15]
Hallo @nightflyer88,
nochmal vielen Dank für die tolle Software und die ausführlichen Beschreibungen hier.
Nach dem letzten Update bekomme ich folgende Fehlermeldung wenn ich mich entweder via DNS Name oder IP versuche zu verbinden:
CGscale Error: 404
 File or URL not Found !
Irgendeine Idee was das sein könnte?
Grüße,
Falko

**Comment by jraichle** [comment]
Hallo Falko,
kann es sein dass Du das hier vergessen hast?
Nach dem die CG scale das erste mal gebootet hat, wird ein Hotspot CG scale generiert, mit diesem WiFi verbindet man sich nun mit dem Computer. Danach den Webbrowser öffnen, und die Adresse: cgscale.local/update eintippen. Es öffnet sich eine kleine Update Webpage, dort wählt man bei Filesystem die Datei CG_scale_spiffs.bin und drückt auf Filesystem update. Nach erfolgtem update bootet die CG scale neu, und ist nun betriebsbereit.
Gruß Jochen

**Comment by fheinze26** [comment]
Mensch Jochen, vielen Dank das wars. Hätte ich auch selber draufkommen können ;) Danke
