### ISSUE TITLE
Sehr große Datei

### ISSUE THREAD

**Issue by Antonio307** [nightflyer88/CG_scale#16]
Hallo, ich habe versucht, das Programm auf 328p und 32u4 hochzuladen, kann es aber nicht.
Die Arduino-IDE gibt einen zu großen Dateifehler zurück.
"C:\\Users\\A_tronc\\AppData\\Local\\Temp\\arduino_build_742244/CG_scale-2.22.ino.elf"
text section exceeds available space in boardSketch uses 33092 bytes (115%) of program storage space. Maximum is 28672 bytes.

Global variables use 1556 bytes (60%) of dynamic memory, leaving 1004 bytes for local variables. Maximum is 2560 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board SparkFun Pro Micro.

Wissen Sie, was passieren könnte?
Vielen Dank.

**Comment by lhm74** [comment]
Hallo habe genau das gleiche Problem.
Wäre schön wenn uns jemand helfen könnte.
Gruß Alexander

**Comment by nightflyer88** [comment]
Der AVR Code ist für einen Atmega328 vorgesehen. Der 32u4 hat zwar einen gleich grossen Flash, der Bootloader ist jedoch grösser, deshalb ist der Code für den 32u4 zu gross. Mit der Arduino IDE 2.0.3 wird der AVR Code für den 328 mit 94% kompiliert.
