### ISSUE TITLE
Frage zur Erstellung der html Seiten von CG Scale

### ISSUE THREAD

**Issue by Fux2** [nightflyer88/CG_scale#18]
Hallo Michael,

leider habe ich keine E-Mail Adresse gefunden, daher als Issue:
Mit welcher Software hast Du denn die verschiedenen html-Seiten für CG Scale erstellt?
Ich möchte für ein anderes Projekt ähnliche Seiten erstellen zum Anzeigen diverser Temperaturen.

Nutzt Du die normale Arduino IDE zum Programmieren?

Danke und Grüße
Fux

**Comment by nightflyer88** [comment]
Hallo Fux

Die html Seiten sind alle von "Hand" programmiert, ohne Designsoftware. Das ESP läuft stabiler wenn html, css, java und images alle in einer Datei sind. Ich kenne keine Software die das so kann...

Gruss Michael
