### ISSUE TITLE
Settings korrekt?

### ISSUE THREAD

**Issue by cszielke** [nightflyer88/CG_scale#22]
in der Datei "settings_WIFI_KIT_8." (Settings for WIFI KIT 8) ist für Loadcell3 folgendes definiert:

#define PIN_LOADCELL3_DOUT            D0
#define PIN_LOADCELL3_PD_SCK          D0

ist das korrekt?
Ich habe leider kein WIFI KIT 8 hier.

**Comment by nightflyer88** [comment]
Das WIFI KIT 8 hat leider zuwenig I/Os deshalb werden nur zwei Loadcells unterstützt, es ist egal was in der 3. Loadcell steht
