### ISSUE TITLE
NodeMCU mit CG Scale Verbindungsprobleme mit lokalem Wifi

### ISSUE THREAD

**Issue by kkberg** [nightflyer88/CG_scale#4]
Leider verbindet sich das System nicht mit dem lokalen WiFi, obwohl SSID und Wlan-Schlüssel korrekt sind. Parameter werden gespeichert und das wird auch bestätigt.
Nach dem Speichern bleibt  CG Scale als SSID, also im AP-Modus, was auch nach Neustart so bleibt.

**Comment by kkberg** [comment]
Es sieht m.E. so aus, dass nicht lange genug nach vorhandenen WiFi's gesucht wird und dadurch direkt in den AP-Modus gewechselt wird.

**Comment by kkberg** [comment]
Ich denke das es diese Stelle ist, die ich verändern muss. 
#define TIMEOUT_CONNECT 25000   //ms

**Comment by nightflyer88** [comment]
Was hast du denn für einen Router ? Es ist möglich das einige etwas mehr Zeit benötigen. Mit 25000ms funktioniert es ?

**Comment by kkberg** [comment]
Ich habe eine Fritzbox 7590. Den Wert habe ich angepasst auf 50000ms und das funktioniert. Ich habe inzwischwn auch eine RS232 to Wifi Bridge gefunden, was für mich noch angenehmer ist. Ost es angedacht so etwas auch noch zu implementieren? Übrigens eine tolle Arbeit die Du gemacht hast. TOP

**Comment by nightflyer88** [comment]
Bis jetzt ist sowas nicht angedacht. Für was brauchst du die Bridge, oder wie funktioniert das genau ?

**Comment by kkberg** [comment]
Ich brauche nur eine Com-Port, ohne eine Oberfläche.

**Comment by kkberg** [comment]
Entschuldige bitte, ich habe das jetzt falsch gepostet. Das sollte hier nicht rein. Ich habe noch ein Projekt mit ESP und mir ist was durcheinander geraten.
