### ISSUE TITLE
Drehmoment des Flügelpaares beim messen des Rumpfes addieren 

### ISSUE THREAD

**Issue by Rolf-G** [nightflyer88/CG_scale#5]
Erst mal vielen Dank für das hervoragende und sehr praxistaugliche Programm. Die Möglichkeit, mehrere Modelle (mit jeweils eigenen Abständen der Wägepunkte/Referenzpunkt) ist genial. Leider reichen meine Programmier Kenntnisse nicht aus, um selbst folgende Erweiterung einzupflegen, daher schlage ich das einfach mal hier vor:

Könnte zur tatsächlichen Messung bedarfsweise ein weiteres "virtuelles" Drehmoment (Gewicht/Abstand) mit gerechnet werden ? 

Nimmt man die abmontierten Flügel und bestimmt deren Schwerpunkt/Gewicht einmal alleine, und nimmt diese Werte dann als "virtuelles" Gewicht, könnte man beim Bauen am Rumpf in der Werkstatt (wo man im allgemeinen ja besonderes bei drößeren Fliegern die Flügel eben nicht montiert hat) allein durch Auswiegen des Rumpfes ablesen, wo später bei montiertem Flächeln der Schwerpunkt sein wird. Man bräuchte zum Überprüfen also nicht jedesmal die Flügel montieren. 

Hoffe, ich habe mich halbwegs verständlich ausgedrückt. 
MfG Rolf

**Comment by nightflyer88** [comment]
Eingebaut bei V2.2

**Comment by Rolf-G** [comment]
Suuuuuuuuuuper, tausend Dank
