### ISSUE TITLE
Meschanischer Aufbau / Druckteile für 3 Wägezellen

### ISSUE THREAD

**Issue by derFrickler** [nightflyer88/CG_scale#6]
Hallo, Vielen Dank für das schöne Projekt. 

Gibts auch irgendwo Bilder des Aufbaus mit 3 Wägezellen, oder evtl sogar passende Druckteile dazu?

Gruß
     Johannes

**Comment by nightflyer88** [comment]
Hallo Johannes

Hier gibt es zwei Varianten:
https://www.thingiverse.com/thing:3711368
https://www.thingiverse.com/thing:3610084

Gruss Michael
