### ISSUE TITLE
Fehler der Version 2.0 beim Kompilieren.

### ISSUE THREAD

**Issue by Skippydi** [nightflyer88/CG_scale#7]
Beim Kompilieren der V2.0 erscheint folgender Fehler:
 
Sketch wird kompiliert...

CG_scale:103:13: error: 'MAX_MODELNAME_LENGHT' was not declared in this scope

   char name[MAX_MODELNAME_LENGHT + 1] = "";

             ^~~~~~~~~~~~~~~~~~~~

Bibliothek HX711_ADC in Version 1.2.1 im Ordner: C:\Users\Skippy\Documents\Arduino\libraries\HX711_ADC  wird verwendet

Bibliothek U8g2 in Version 2.27.6 im Ordner: C:\Users\Skippy\Documents\Arduino\libraries\U8g2  wird verwendet

Bibliothek EEPROM in Version 2.0 im Ordner: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\EEPROM  wird verwendet

Bibliothek Wire in Version 1.0 im Ordner: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire  wird verwendet

Bibliothek SPI in Version 1.0 im Ordner: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI  wird verwendet

exit status 1

'MAX_MODELNAME_LENGHT' was not declared in this scope

Mein Fehler oder, fehlt das was??

Gruß Dietmar

**Comment by Skippydi** [comment]
Hat sich erledigt

**Comment by fheinze26** [comment]
Hi @Skippydi und @nightflyer88 
ich versuche gerade die Version 2.0 auf einen Arduino UNO zu installiere und bekomme eine ganz ähnlich Fehlermeldung. Wie habt ihr das Problem gelöst? VIELEN DANK

Arduino: 1.8.12 (Mac OS X), Board: "Arduino Uno"

In file included from /Users/fheinze/Downloads/CG_scale/CG_scale.ino:83:0:
settings_AVR.h:54:39: error: 'A9' was not declared in this scope
 #define PIN_LOADCELL3_DOUT            A9
                                       ^
/Users/fheinze/Downloads/CG_scale/CG_scale.ino:89:136: note: in expansion of macro 'PIN_LOADCELL3_DOUT'
 HX711_ADC LoadCell[]{HX711_ADC(PIN_LOADCELL1_DOUT, PIN_LOADCELL1_PD_SCK),HX711_ADC(PIN_LOADCELL2_DOUT, PIN_LOADCELL2_PD_SCK),HX711_ADC(PIN_LOADCELL3_DOUT, PIN_LOADCELL3_PD_SCK)};
                                                                                                                                        ^~~~~~~~~~~~~~~~~~
sketch/settings_AVR.h:54:39: note: suggested alternative: 'A7'
 #define PIN_LOADCELL3_DOUT            A9
                                       ^
/Users/fheinze/Downloads/CG_scale/CG_scale.ino:89:136: note: in expansion of macro 'PIN_LOADCELL3_DOUT'
 HX711_ADC LoadCell[]{HX711_ADC(PIN_LOADCELL1_DOUT, PIN_LOADCELL1_PD_SCK),HX711_ADC(PIN_LOADCELL2_DOUT, PIN_LOADCELL2_PD_SCK),HX711_ADC(PIN_LOADCELL3_DOUT, PIN_LOADCELL3_PD_SCK)};
                                                                                                                                        ^~~~~~~~~~~~~~~~~~
settings_AVR.h:55:39: error: 'A10' was not declared in this scope
 #define PIN_LOADCELL3_PD_SCK          A10
                                       ^
/Users/fheinze/Downloads/CG_scale/CG_scale.ino:89:156: note: in expansion of macro 'PIN_LOADCELL3_PD_SCK'
 HX711_ADC LoadCell[]{HX711_ADC(PIN_LOADCELL1_DOUT, PIN_LOADCELL1_PD_SCK),HX711_ADC(PIN_LOADCELL2_DOUT, PIN_LOADCELL2_PD_SCK),HX711_ADC(PIN_LOADCELL3_DOUT, PIN_LOADCELL3_PD_SCK)};
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~
sketch/settings_AVR.h:55:39: note: suggested alternative: 'A1'
 #define PIN_LOADCELL3_PD_SCK          A10
                                       ^
/Users/fheinze/Downloads/CG_scale/CG_scale.ino:89:156: note: in expansion of macro 'PIN_LOADCELL3_PD_SCK'
 HX711_ADC LoadCell[]{HX711_ADC(PIN_LOADCELL1_DOUT, PIN_LOADCELL1_PD_SCK),HX711_ADC(PIN_LOADCELL2_DOUT, PIN_LOADCELL2_PD_SCK),HX711_ADC(PIN_LOADCELL3_DOUT, PIN_LOADCELL3_PD_SCK)};
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~
CG_scale:103:13: error: 'MAX_MODELNAME_LENGHT' was not declared in this scope
   char name[MAX_MODELNAME_LENGHT + 1] = "";
             ^~~~~~~~~~~~~~~~~~~~
exit status 1
'A9' was not declared in this scope

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by Skippydi** [comment]
Das Problem ist, das die Firmware für einen ESP8266 geschrieben wurde. Mit einem ESP hatte ich den Fehler nicht mehr. Außerdem ist der auch erheblich komfortabler mit WLAN.

**Comment by fheinze26** [comment]
Danke für die schnelle Antwort @Skippydi
Ich habe jetzt alle Versionen bis 1.0 durchprobiert und immer erhalten ich denselben Fehler "A9' was not declared in this scope" - Es scheint im allgemeinen nicht mit dem ATmega328 zu funktionieren oder ich mach was falsch. Dann probiere ich mal einen ESP8266. Ist nur schade weil ich noch ein paar Arduino UNOs zuhause rumliegen habe. Danke nochmal

**Comment by Skippydi** [comment]
Der UNO hat keinen A9 Input/Output das ist das Problem

Von meinem iPhone gesendet

**Comment by fheinze26** [comment]
Stimmt, der hat ja nur Analog A0-A5 jetzt wo Du´s sagst, macht total Sinn ;)
