### ISSUE TITLE
Tara Button auf Kalibrierungs-Seite

### ISSUE THREAD

**Issue by Blackforrestpilot** [nightflyer88/CG_scale#9]
Verbesserungsvorschlag:
Einen Tara Button auf der Kalibrierungs Seite einfügen.
Das Kalibrieren wird dann vereinfacht und weniger fehlerfällig.
Ich würde das gerne selber programmieren,finde aber die Sourcen der Web GUI nicht.

Gruss
Christoph

**Comment by nightflyer88** [comment]
Habe ich nun eingebaut, ist aber noch nicht getestet: d1ad6b6c4293ef6ffc48abfb7cc4e12905cb4f5f
